- name: gather OS family
  hosts: all
  tasks:
    - name: get OS family
      debug:
        msg: "The OS family is {{ ansible_facts.os_family }}"
    - name: get IP Address
      debug:
        msg: "The IP address is {{ ansible_default_ipv4.address}}"
    - name: get IP Address
      debug:
        msg: "The IP address is {{ inventory_hostname}}"
    - name: get IP Address
      debug:
        msg: "The IP address is {{ansible_distribution}}"